In [1]:
import pandas as pd

In [11]:
def process_lookup(path):
    df = pd.read_csv(path)
    df['Q'] = df[pd.notnull(df['Total Cells in Table'])]['Table Title']
    df['Q'] = df['Q'].fillna(method='ffill')
    df = df[df['Line Number'].str.strip().str.len() >0]
    df['A'] = df[df['Table Title'].str.endswith(':')]['Table Title']
    df['A'] = df.groupby(['Table ID', 'Q'])['A'].transform(lambda group: group.ffill())
    df['Column'] = df['Sequence Number'].astype(str) +'_' + df['Line Number'].astype(str)
    return df[['Table ID', 'Column', 'Q', 'A','Table Title']]

In [12]:
pa = process_lookup('../../Data/raw_aggData/lookup_table20131Y.csv')
ba = process_lookup('../../Data/raw_aggData/lookup_table20135Y.csv')

In [15]:
pa

,Table ID,Column,Q,A,Table Title
2,B00001,1_1,UNWEIGHTED SAMPLE COUNT OF THE POPULATION,NaN,Total
5,B00002,1_1,UNWEIGHTED SAMPLE HOUSING UNITS,NaN,Total
8,B01001,2_1,SEX BY AGE,Total:,Total:
9,B01001,2_2,SEX BY AGE,Male:,Male:
10,B01001,2_3,SEX BY AGE,Male:,Under 5 years
11,B01001,2_4,SEX BY AGE,Male:,5 to 9 years
12,B01001,2_5,SEX BY AGE,Male:,10 to 14 years
13,B01001,2_6,SEX BY AGE,Male:,15 to 17 years
14,B01001,2_7,SEX BY AGE,Male:,18 and 19 years
15,B01001,2_8,SEX BY AGE,Male:,20 years
16,B01001,2_9,SEX BY AGE,Male:,21 years
17,B01001,2_10,SEX BY AGE,Male:,22 to 24 years
18,B01001,2_11,SEX BY AGE,Male:,25 to 29 years
19,B01001,2_12,SEX BY AGE,Male:,30 to 34 years
20,B01001,2_13,SEX BY AGE,Male:,35 to 39 years
21,B01001,2_14,SEX BY AGE,Male:,40 to 44 years
22,B01001,2_15,SEX BY AGE,Male:,45 to 49 years
23,B01001,2_16,SEX BY AGE,Male:,50 to 54 years
24,B01001,2_17,SEX BY AGE,Male:,55 to 59 years
25,B01001,2_18,SEX BY AGE,Male:,60 and 61 years
26,B01001,2_19,SEX BY AGE,Male:,62 to 64 years
27,B01001,2_20,SEX BY AGE,Male:,65 and 66 years
28,B01001,2_21,SEX BY AGE,Male:,67 to 69 years
29,B01001,2_22,SEX BY AGE,Male:,70 to 74 years
30,B01001,2_23,SEX BY AGE,Male:,75 to 79 years
31,B01001,2_24,SEX BY AGE,Male:,80 to 84 years
32,B01001,2_25,SEX BY AGE,Male:,85 years and over
33,B01001,2_26,SEX BY AGE,Female:,Female:
34,B01001,2_27,SEX BY AGE,Female:,Under 5 years
35,B01001,2_28,SEX BY AGE,Female:,5 to 9 years
...,...,...,...,...,...
35630,B992706,170_3,IMPUTATION OF MEDICARE COVERAGE,Total:,Not imputed
35633,B992707,170_1,IMPUTATION OF MEDICAID/MEANS-TESTED PUBLIC COV...,Total:,Total:
35634,B992707,170_2,IMPUTATION OF MEDICAID/MEANS-TESTED PUBLIC COV...,Total:,Imputed
35635,B992707,170_3,IMPUTATION OF MEDICAID/MEANS-TESTED PUBLIC COV...,Total:,Not imputed
35638,B992708,170_1,IMPUTATION OF TRICARE/MILITARY HEALTH COVERAGE,Total:,Total:
35639,B992708,170_2,IMPUTATION OF TRICARE/MILITARY HEALTH COVERAGE,Total:,Imputed
35640,B992708,170_3,IMPUTATION OF TRICARE/MILITARY HEALTH COVERAGE,Total:,Not imputed
35643,B992709,170_1,IMPUTATION OF VA HEALTH CARE,Total:,Total:
35644,B992709,170_2,IMPUTATION OF VA HEALTH CARE,Total:,Imputed
35645,B992709,170_3,IMPUTATION OF VA HEALTH CARE,Total:,Not imputed
35648,B99281,170_1,IMPUTATION OF HOUSEHOLD INTERNET ACCESS,Total:,Total:
35649,B99281,170_2,IMPUTATION OF HOUSEHOLD INTERNET ACCESS,Total:,Imputed
35650,B99281,170_3,IMPUTATION OF HOUSEHOLD INTERNET ACCESS,Total:,Not imputed
35653,B99282,170_1,IMPUTATION OF HOUSEHOLD COMPUTER TYPE,Total:,Total:
35654,B99282,170_1.5,IMPUTATION OF HOUSEHOLD COMPUTER TYPE,Desktop or laptop:,Desktop or laptop:
35655,B99282,170_2,IMPUTATION OF HOUSEHOLD COMPUTER TYPE,Desktop or laptop:,Imputed
35656,B99282,170_3,IMPUTATION OF HOUSEHOLD COMPUTER TYPE,Desktop or laptop:,Not imputed
35657,B99282,170_3.5,IMPUTATION OF HOUSEHOLD COMPUTER TYPE,Handheld computer:,Handheld computer:
35658,B99282,170_4,IMPUTATION OF HOUSEHOLD COMPUTER TYPE,Handheld computer:,Imputed
35659,B99282,170_5,IMPUTATION OF HOUSEHOLD COMPUTER TYPE,Handheld computer:,Not imputed
35660,B99282,170_5.5,IMPUTATION OF HOUSEHOLD COMPUTER TYPE,Other computer:,Other computer:
35661,B99282,170_6,IMPUTATION OF HOUSEHOLD COMPUTER TYPE,Other computer:,Imputed
35662,B99282,170_7,IMPUTATION OF HOUSEHOLD COMPUTER TYPE,Other computer:,Not imputed
35665,B99283,170_1,IMPUTATION OF HOUSEHOLD INTERNET SUBSCRIPTION ...,Total:,Total:
35666,B99283,170_1.5,IMPUTATION OF HOUSEHOLD INTERNET SUBSCRIPTION ...,Imputed:,Imputed:
35667,B99283,170_2,IMPUTATION OF HOUSEHOLD INTERNET SUBSCRIPTION ...,Imputed:,Dial-up
35668,B99283,170_3,IMPUTATION OF HOUSEHOLD INTERNET SUBSCRIPTION ...,Imputed:,DSL
35669,B99283,170_4,IMPUTATION OF HOUSEHOLD INTERNET SUBSCRIPTION ...,Imputed:,"Cable modem, fiber-optic, satellite internet s..."
35670,B99283,170_5,IMPUTATION OF HOUSEHOLD INTERNET SUBSCRIPTION ...,Imputed:,Mobile broadband
35671,B99283,170_6,IMPUTATION OF HOUSEHOLD INTERNET SUBSCRIPTION ...,Imputed:,Not imputed

In [16]:
ba

,Table ID,Column,Q,A,Table Title
2,B00001,1_1,UNWEIGHTED SAMPLE COUNT OF THE POPULATION,NaN,Total
5,B00002,1_1,UNWEIGHTED SAMPLE HOUSING UNITS,NaN,Total
8,B01001,2_1,SEX BY AGE,Total:,Total:
9,B01001,2_2,SEX BY AGE,Male:,Male:
10,B01001,2_3,SEX BY AGE,Male:,Under 5 years
11,B01001,2_4,SEX BY AGE,Male:,5 to 9 years
12,B01001,2_5,SEX BY AGE,Male:,10 to 14 years
13,B01001,2_6,SEX BY AGE,Male:,15 to 17 years
14,B01001,2_7,SEX BY AGE,Male:,18 and 19 years
15,B01001,2_8,SEX BY AGE,Male:,20 years
16,B01001,2_9,SEX BY AGE,Male:,21 years
17,B01001,2_10,SEX BY AGE,Male:,22 to 24 years
18,B01001,2_11,SEX BY AGE,Male:,25 to 29 years
19,B01001,2_12,SEX BY AGE,Male:,30 to 34 years
20,B01001,2_13,SEX BY AGE,Male:,35 to 39 years
21,B01001,2_14,SEX BY AGE,Male:,40 to 44 years
22,B01001,2_15,SEX BY AGE,Male:,45 to 49 years
23,B01001,2_16,SEX BY AGE,Male:,50 to 54 years
24,B01001,2_17,SEX BY AGE,Male:,55 to 59 years
25,B01001,2_18,SEX BY AGE,Male:,60 and 61 years
26,B01001,2_19,SEX BY AGE,Male:,62 to 64 years
27,B01001,2_20,SEX BY AGE,Male:,65 and 66 years
28,B01001,2_21,SEX BY AGE,Male:,67 to 69 years
29,B01001,2_22,SEX BY AGE,Male:,70 to 74 years
30,B01001,2_23,SEX BY AGE,Male:,75 to 79 years
31,B01001,2_24,SEX BY AGE,Male:,80 to 84 years
32,B01001,2_25,SEX BY AGE,Male:,85 years and over
33,B01001,2_26,SEX BY AGE,Female:,Female:
34,B01001,2_27,SEX BY AGE,Female:,Under 5 years
35,B01001,2_28,SEX BY AGE,Female:,5 to 9 years
...,...,...,...,...,...
24909,B99259,122_1,IMPUTATION OF PLUMBING FACILITIES,Total:,Total:
24910,B99259,122_2,IMPUTATION OF PLUMBING FACILITIES,Total:,Imputed
24911,B99259,122_3,IMPUTATION OF PLUMBING FACILITIES,Total:,Not imputed
24914,B992701,122_1,IMPUTATION OF HEALTH INSURANCE COVERAGE,Total:,Total:
24915,B992701,122_2,IMPUTATION OF HEALTH INSURANCE COVERAGE,Total:,One or more health insurance items imputed
24916,B992701,122_3,IMPUTATION OF HEALTH INSURANCE COVERAGE,Total:,No health insurance items imputed
24919,B992702,122_1,IMPUTATION OF PRIVATE HEALTH INSURANCE,Total:,Total:
24920,B992702,122_2,IMPUTATION OF PRIVATE HEALTH INSURANCE,Total:,One or more private health insurance items imp...
24921,B992702,122_3,IMPUTATION OF PRIVATE HEALTH INSURANCE,Total:,No private health insurance items imputed
24924,B992703,122_1,IMPUTATION OF PUBLIC HEALTH INSURANCE,Total:,Total:
24925,B992703,122_2,IMPUTATION OF PUBLIC HEALTH INSURANCE,Total:,One or more public coverage items imputed
24926,B992703,122_3,IMPUTATION OF PUBLIC HEALTH INSURANCE,Total:,No public coverage items imputed
24929,B992704,122_1,IMPUTATION OF EMPLOYER-BASED HEALTH INSURANCE,Total:,Total:
24930,B992704,122_2,IMPUTATION OF EMPLOYER-BASED HEALTH INSURANCE,Total:,Imputed
24931,B992704,122_3,IMPUTATION OF EMPLOYER-BASED HEALTH INSURANCE,Total:,Not imputed
24934,B992705,122_1,IMPUTATION OF DIRECT-PURCHASE HEALTH INSURANCE,Total:,Total:
24935,B992705,122_2,IMPUTATION OF DIRECT-PURCHASE HEALTH INSURANCE,Total:,Imputed
24936,B992705,122_3,IMPUTATION OF DIRECT-PURCHASE HEALTH INSURANCE,Total:,Not imputed
24939,B992706,122_1,IMPUTATION OF MEDICARE COVERAGE,Total:,Total:
24940,B992706,122_2,IMPUTATION OF MEDICARE COVERAGE,Total:,Imputed
24941,B992706,122_3,IMPUTATION OF MEDICARE COVERAGE,Total:,Not imputed
24944,B992707,122_1,IMPUTATION OF MEDICAID/MEANS-TESTED PUBLIC COV...,Total:,Total:
24945,B992707,122_2,IMPUTATION OF MEDICAID/MEANS-TESTED PUBLIC COV...,Total:,Imputed
24946,B992707,122_3,IMPUTATION OF MEDICAID/MEANS-TESTED PUBLIC COV...,Total:,Not imputed
24949,B992708,122_1,IMPUTATION OF TRICARE/MILITARY HEALTH COVERAGE,Total:,Total:
24950,B992708,122_2,IMPUTATION OF TRICARE/MILITARY HEALTH COVERAGE,Total:,Imputed
24951,B992708,122_3,IMPUTATION OF TRICARE/MILITARY HEALTH COVERAGE,Total:,Not imputed
24954,B992709,122_1,IMPUTATION OF VA HEALTH CARE,Total:,Total:
24955,B992709,122_2,IMPUTATION OF VA HEALTH CARE,Total:,Imputed
24956,B992709,122_3,IMPUTATION OF VA HEALTH CARE,Total:,Not imputed

# Intersecting Table ID's

In [17]:
len([ x for x in pa['Table ID'].unique().tolist() if x in ba['Table ID'].unique().tolist()])

1040

In [18]:
df = pa.merge(ba, how='inner', on=['Table ID','Q', 'A', 'Table Title'])
df.rename(columns={'Column_x':'puma_attr', 'Column_y':'block_attr'}, inplace=1)

In [19]:
df.shape

(43243, 6)

In [20]:
df.Q = df.Q.str.lower()
df['Table Title'] = df['Table Title'].str.lower()

In [21]:
# dropping all imputations
df = df[~df['Q'].str.contains('imputation')]
df.shape

(42803, 6)

In [22]:
# dropping all samples
df = df[~df['Q'].str.contains('sample')]
df.shape

(42796, 6)

In [25]:
df['Q_name'] = df.apply(lambda x:'%s_%s_%s_%s' % (x['Table ID'],x['Q'],x['A'],x['Table Title']),axis=1)

In [27]:
df[df['puma_attr']!=df['block_attr']]

,Table ID,puma_attr,Q,A,Table Title,block_attr,Q_name
406,B03001,6_1,hispanic or latino origin by specific origin,Total:,total:,5_1,B03001_hispanic or latino origin by specific o...
407,B03001,6_2,hispanic or latino origin by specific origin,Total:,not hispanic or latino,5_2,B03001_hispanic or latino origin by specific o...
408,B03001,6_3,hispanic or latino origin by specific origin,Hispanic or Latino:,hispanic or latino:,5_3,B03001_hispanic or latino origin by specific o...
409,B03001,6_4,hispanic or latino origin by specific origin,Hispanic or Latino:,mexican,5_4,B03001_hispanic or latino origin by specific o...
410,B03001,6_5,hispanic or latino origin by specific origin,Hispanic or Latino:,puerto rican,5_5,B03001_hispanic or latino origin by specific o...
411,B03001,6_6,hispanic or latino origin by specific origin,Hispanic or Latino:,cuban,5_6,B03001_hispanic or latino origin by specific o...
412,B03001,6_7,hispanic or latino origin by specific origin,Hispanic or Latino:,dominican (dominican republic),5_7,B03001_hispanic or latino origin by specific o...
413,B03001,6_8,hispanic or latino origin by specific origin,Central American:,central american:,5_8,B03001_hispanic or latino origin by specific o...
414,B03001,6_9,hispanic or latino origin by specific origin,Central American:,costa rican,5_9,B03001_hispanic or latino origin by specific o...
415,B03001,6_10,hispanic or latino origin by specific origin,Central American:,guatemalan,5_10,B03001_hispanic or latino origin by specific o...
416,B03001,6_11,hispanic or latino origin by specific origin,Central American:,honduran,5_11,B03001_hispanic or latino origin by specific o...
417,B03001,6_12,hispanic or latino origin by specific origin,Central American:,nicaraguan,5_12,B03001_hispanic or latino origin by specific o...
418,B03001,6_13,hispanic or latino origin by specific origin,Central American:,panamanian,5_13,B03001_hispanic or latino origin by specific o...
419,B03001,6_14,hispanic or latino origin by specific origin,Central American:,salvadoran,5_14,B03001_hispanic or latino origin by specific o...
420,B03001,6_15,hispanic or latino origin by specific origin,Central American:,other central american,5_15,B03001_hispanic or latino origin by specific o...
421,B03001,6_16,hispanic or latino origin by specific origin,South American:,south american:,5_16,B03001_hispanic or latino origin by specific o...
422,B03001,6_17,hispanic or latino origin by specific origin,South American:,argentinean,5_17,B03001_hispanic or latino origin by specific o...
423,B03001,6_18,hispanic or latino origin by specific origin,South American:,bolivian,5_18,B03001_hispanic or latino origin by specific o...
424,B03001,6_19,hispanic or latino origin by specific origin,South American:,chilean,5_19,B03001_hispanic or latino origin by specific o...
425,B03001,6_20,hispanic or latino origin by specific origin,South American:,colombian,5_20,B03001_hispanic or latino origin by specific o...
426,B03001,6_21,hispanic or latino origin by specific origin,South American:,ecuadorian,5_21,B03001_hispanic or latino origin by specific o...
427,B03001,6_22,hispanic or latino origin by specific origin,South American:,paraguayan,5_22,B03001_hispanic or latino origin by specific o...
428,B03001,6_23,hispanic or latino origin by specific origin,South American:,peruvian,5_23,B03001_hispanic or latino origin by specific o...
429,B03001,6_24,hispanic or latino origin by specific origin,South American:,uruguayan,5_24,B03001_hispanic or latino origin by specific o...
430,B03001,6_25,hispanic or latino origin by specific origin,South American:,venezuelan,5_25,B03001_hispanic or latino origin by specific o...
431,B03001,6_26,hispanic or latino origin by specific origin,South American:,other south american,5_26,B03001_hispanic or latino origin by specific o...
432,B03001,6_27,hispanic or latino origin by specific origin,Other Hispanic or Latino:,other hispanic or latino:,5_27,B03001_hispanic or latino origin by specific o...
433,B03001,6_28,hispanic or latino origin by specific origin,Other Hispanic or Latino:,spaniard,5_28,B03001_hispanic or latino origin by specific o...
434,B03001,6_29,hispanic or latino origin by specific origin,Other Hispanic or Latino:,spanish,5_29,B03001_hispanic or latino origin by specific o...
435,B03001,6_30,hispanic or latino origin by specific origin,Other Hispanic or Latino:,spanish american,5_30,B03001_hispanic or latino origin by specific o...
...,...,...,...,...,...,...,...
42773,B98012,166_2,total population coverage rate by sex,Total:,male,118_2,B98012_total population coverage rate by sex_T...
42774,B98012,166_3,total population coverage rate by sex,Total:,female,118_3,B98012_total population coverage rate by sex_T...
42775,B98013,166_1,total population coverage rate by weighting ra...,Total:,total:,118_1,B98013_total population coverage rate by weigh...
42776,B98013,166_1.5,total population coverage rate by weighting ra...,Not Hispanic or Latino:,not hispanic or latino:,118_1.5,B98013_total population coverage rate by weigh...
42777,B98013,166_2,total population coverage rate by weighting ra...,Not Hispanic or Latino:,white,118_2,B98013_total population coverage rate by weigh...
42778,B98013,166_3,total population coverage rate by weighting ra...,Not Hispanic or Latino:,black or african american,118_3,B98013_total population coverage rate by weigh...
42779,B98013,166_4,total population coverage rate by weighting ra...,Not Hispanic or Latino:,american indian and alaska native,118_4,B98013_total population coverage rate by weigh...
42780,B98013,166_5,total population coverage rate by weighting ra...,Not Hispanic or Latino:,asian,118_5,B98013_total population coverage rate by weigh...
42781,B98013,166_6,total population coverage rate by weighting ra...,Not Hispanic or Latino:,native hawaiian and other pacific islander,118_6,B98013_total population coverage rate by weigh...
42782,B98013,166_7,total population coverage rate by weighting ra...,Not Hispanic or Latino:,hispanic or latino,118_7,B98013_total population coverage rate by weigh...
42783,B98014,166_1,group quarters population coverage rate,NaN,total,118_1,B98014_group quarters population coverage rate...
42784,B98021,166_1,housing unit response and nonresponse rates wi...,NaN,response rate,118_1,B98021_housing unit response and nonresponse r...
42785,B98021,166_2,housing unit response and nonresponse rates wi...,Nonresponse Rate:,nonresponse rate:,118_2,B98021_housing unit response and nonresponse r...
42786,B98021,166_3,housing unit response and nonresponse rates wi...,Nonresponse Rate:,refusal,118_3,B98021_housing unit response and nonresponse r...
42787,B98021,166_4,housing unit response and nonresponse rates wi...,Nonresponse Rate:,unable to locate,118_4,B98021_housing unit response and nonresponse r...
42788,B98021,166_5,housing unit response and nonresponse rates wi...,Nonresponse Rate:,no one home,118_5,B98021_housing unit response and nonresponse r...
42789,B98021,166_6,housing unit response and nonresponse rates wi...,Nonresponse Rate:,temporarily absent,118_6,B98021_housing unit response and nonresponse r...
42790,B98021,166_7,housing unit response and nonresponse rates wi...,Nonresponse Rate:,language problem,118_7,B98021_housing unit response and nonresponse r...
42791,B98021,166_8,housing unit response and nonresponse rates wi...,Nonresponse Rate:,insufficient data,118_8,B98021_housing unit response and nonresponse r...
42792,B98021,166_9,housing unit response and nonresponse rates wi...,Nonresponse Rate:,other reason,118_9,B98021_housing unit response and nonresponse r...
42793,B98022,166_1,group quarters population response and nonresp...,NaN,response rate,118_1,B98022_group quarters population response and ...
42794,B98022,166_2,group quarters population response and nonresp...,Nonresponse Rate:,nonresponse rate:,118_2,B98022_group quarters population response and ...
42795,B98022,166_3,group quarters population response and nonresp...,Nonresponse Rate:,group quarters person refusal,118_3,B98022_group quarters population response and ...
42796,B98022,166_4,group quarters population response and nonresp...,Nonresponse Rate:,unable to locate group quarters person,118_4,B98022_group quarters population response and ...
42797,B98022,166_5,group quarters population response and nonresp...,Nonresponse Rate:,resident temporarily absent,118_5,B98022_group quarters population response and ...
42798,B98022,166_6,group quarters population response and nonresp...,Nonresponse Rate:,language problem,118_6,B98022_group quarters population response and ...
42799,B98022,166_7,group quarters population response and nonresp...,Nonresponse Rate:,insufficient data,118_7,B98022_group quarters population response and ...
42800,B98022,166_8,group quarters population response and nonresp...,Nonresponse Rate:,group quarters person other reason,118_8,B98022_group quarters population response and ...
42801,B98022,166_9,group quarters population response and nonresp...,Nonresponse Rate:,whole group quarters refusal,118_9,B98022_group quarters population response and ...
42802,B98022,166_10,group quarters population response and nonresp...,Nonresponse Rate:,whole group quarters other reason,118_10,B98022_group quarters population response and ...

In [29]:
r = df[['Q_name', 'puma_attr','block_attr']]

In [31]:
r.to_csv('../../Data/raw_aggData/attr_interconn.csv')