In [1]:
import pandas as pd

C:\Users\Alan\Anaconda\lib\site-packages\pandas\computation\__init__.py:19: UserWarning: The installed version of numexpr 2.4.4 is not supported in pandas and will be not be used

  UserWarning)

In [2]:
pumas = pd.read_csv('../../Data/geo_id/pumas.csv', index_col=0, dtype='str')[[4, 49]]
bgs = pd.read_csv('../../Data/geo_id/bg.csv', index_col=0, dtype='str')[[4, 49]]

IOError: File ../../Data/geo_id/pumas.csv does not exist

In [35]:
bgs

             4                                                 49
8302   0008303  Block Group 1, Census Tract 1, Albany County, ...
8303   0008304  Block Group 2, Census Tract 1, Albany County, ...
8304   0008305  Block Group 1, Census Tract 2, Albany County, ...
8305   0008306  Block Group 2, Census Tract 2, Albany County, ...
8306   0008307  Block Group 3, Census Tract 2, Albany County, ...
8307   0008308  Block Group 4, Census Tract 2, Albany County, ...
8308   0008309  Block Group 1, Census Tract 3, Albany County, ...
8309   0008310  Block Group 2, Census Tract 3, Albany County, ...
8310   0008311  Block Group 3, Census Tract 3, Albany County, ...
8311   0008312  Block Group 4, Census Tract 3, Albany County, ...
8312   0008313  Block Group 1, Census Tract 4.01, Albany Count...
8313   0008314  Block Group 1, Census Tract 4.03, Albany Count...
8314   0008315  Block Group 2, Census Tract 4.03, Albany Count...
8315   0008316  Block Group 3, Census Tract 4.03, Albany Count...
8316   0008317  Block Group 4, Census Tract 4.03, Albany Count...
8317   0008318  Block Group 1, Census Tract 4.04, Albany Count...
8318   0008319  Block Group 1, Census Tract 5.01, Albany Count...
8319   0008320  Block Group 2, Census Tract 5.01, Albany Count...
8320   0008321  Block Group 3, Census Tract 5.01, Albany Count...
8321   0008322  Block Group 4, Census Tract 5.01, Albany Count...
8322   0008323  Block Group 1, Census Tract 5.02, Albany Count...
8323   0008324  Block Group 2, Census Tract 5.02, Albany Count...
8324   0008325  Block Group 1, Census Tract 6, Albany County, ...
8325   0008326  Block Group 2, Census Tract 6, Albany County, ...
8326   0008327  Block Group 3, Census Tract 6, Albany County, ...
8327   0008328  Block Group 1, Census Tract 7, Albany County, ...
8328   0008329  Block Group 2, Census Tract 7, Albany County, ...
8329   0008330  Block Group 3, Census Tract 7, Albany County, ...
8330   0008331  Block Group 4, Census Tract 7, Albany County, ...
8331   0008332  Block Group 1, Census Tract 8, Albany County, ...
...        ...                                                ...
23735  0023736  Block Group 2, Census Tract 9709, Wyoming Coun...
23736  0023737  Block Group 3, Census Tract 9709, Wyoming Coun...
23737  0023738  Block Group 1, Census Tract 9710, Wyoming Coun...
23738  0023739  Block Group 2, Census Tract 9710, Wyoming Coun...
23739  0023740  Block Group 3, Census Tract 9710, Wyoming Coun...
23740  0023741  Block Group 4, Census Tract 9710, Wyoming Coun...
23741  0023742  Block Group 1, Census Tract 9711, Wyoming Coun...
23742  0023743  Block Group 2, Census Tract 9711, Wyoming Coun...
23743  0023744  Block Group 3, Census Tract 9711, Wyoming Coun...
23744  0023745  Block Group 1, Census Tract 1501, Yates County...
23745  0023746  Block Group 2, Census Tract 1501, Yates County...
23746  0023747  Block Group 3, Census Tract 1501, Yates County...
23747  0023748  Block Group 4, Census Tract 1501, Yates County...
23748  0023749  Block Group 5, Census Tract 1501, Yates County...
23749  0023750  Block Group 6, Census Tract 1501, Yates County...
23750  0023751  Block Group 1, Census Tract 1502, Yates County...
23751  0023752  Block Group 2, Census Tract 1502, Yates County...
23752  0023753  Block Group 3, Census Tract 1502, Yates County...
23753  0023754  Block Group 1, Census Tract 1503, Yates County...
23754  0023755  Block Group 2, Census Tract 1503, Yates County...
23755  0023756  Block Group 3, Census Tract 1503, Yates County...
23756  0023757  Block Group 4, Census Tract 1503, Yates County...
23757  0023758  Block Group 1, Census Tract 1504, Yates County...
23758  0023759  Block Group 2, Census Tract 1504, Yates County...
23759  0023760  Block Group 3, Census Tract 1504, Yates County...
23760  0023761  Block Group 4, Census Tract 1504, Yates County...
23761  0023762  Block Group 1, Census Tract 1505, Yates County...
23762  0023763  Block Group 2, Census Tract 1505, Yates County...
23763  0023764  Block Group 3, Census Tract 1505, Yates County...
23764  0023765  Block Group 4, Census Tract 1505, Yates County...

[15463 rows x 2 columns]